### ISSUE TITLE
Deaktiver links i footeren

### ISSUE THREAD

**Issue by bentreadwell** [bentreadwell/takemytime#2]
Vi skal have deaktiveret de links vi ikke bruger i footeren, og route dem vi gør til diverse undersider - f.eks. skal Google og IOS knapperne linke til venteliste siden.

**Comment by jacobstentoft** [comment]
Evt. en :hover - underline på links i footer

**Comment by jacobstentoft** [comment]
Og mailen i footer skal også have en :mailto

**Comment by jacobstentoft** [comment]
Måske bytte rundt på information og download app i footer?
